export type Language = 'Commun'
  | 'Elfe'
  | 'Géant'
  | 'Gnome'
  | 'Gobelin'
  | 'Halfelin'
  | 'Nain'
  | 'Orc'
  | 'Abyssal'
  | 'Céleste'
  | 'Commun des profondeurs'
  | 'Draconique'
  | 'Infernal'
  | 'Primordial'
  | 'Noir parler'
  | 'Sselish'
  | 'Sylvestre'
  | 'Sseslish';
